### ISSUE TITLE
Class 'Crm\ZlavomatModule\Gateways\Zlavomat' not found

### ISSUE THREAD

**Issue by PayteR** [remp2020/crm-invoices-module#1]
Error `Class 'Crm\ZlavomatModule\Gateways\Zlavomat' not found` occurs on `/payments/payments/my` url. Problem is in `invoide_button.latte` file on line `28`

![image](https://user-images.githubusercontent.com/1248565/73504655-6ed60600-43d0-11ea-9186-db2ead3850f0.png)

**Comment by markoph** [comment]
Thank you for bug report. We'll remove it.

**Comment by PayteR** [comment]
@markoph this bug is still present

**Comment by rootpd** [comment]
Fixed in `0.11`.
