### ISSUE TITLE
"Preddavok" is without tax

### ISSUE THREAD

**Issue by PayteR** [remp2020/crm-invoices-module#2]
Why is "preddavok" without tax? I think it's a bug

![image](https://user-images.githubusercontent.com/1248565/73505321-70a0c900-43d2-11ea-9d56-a4f4c6ce200d.png)

**Comment by markoph** [comment]
Zero VAT for prepayment _(Preddavok)_ was a requirement of our accountants. We'll make it configurable.

Meanwhile you can make copy of invoice template and change it. See this section in README:

> If you want to use your own layout, prepare your own template with the use of variables described above.  
> Once it's ready, add following snippet to your `app/config/config.local.neon` file (alter as needed):
>  
> ```neon
> invoiceGenerator:
> 	setup:
> 		- setTemplateFile('%appDir%/modules/FooModule/templates/invoices/foo.latte')
> ``` 
>  
> The snippet tells to invoice generator to use template provided at given path instead of default template.

**Comment by PayteR** [comment]
thank you

**Comment by rootpd** [comment]
After consulting this with accountants, we'll not be implementing configurable tax for "advance payment item". The way how CRM currently works is that it delivers the service (subscription, products) and generates the invoice only when the payment is confirmed (the money are transfered). 

In this scenario, "preddavok" should always be in zero tax mode and making it configurable would create opportunity to generate invalid invoices. That's not something the CRM should support.
